app/styles/knihy-roka.scss, app/views/mixins/knihy-roka/bookHorizontal.pug
@matusmarcin este som trochu vylepsil responsive
=> polish responsiveness

app/styles/knihy-roka.scss, app/views/data/knihy-roka.yaml, app/views/knihy-roka-dizajn.pug, app/views/knihy-roka-popularno-naucna-literatura.pug, app/views/knihy-roka-pre-deti-vo-veku-11-13-rokov.pug, app/views/knihy-roka-pre-deti-vo-veku-14-16-rokov.pug, app/views/knihy-roka-pre-deti-vo-veku-4-6-rokov.pug, app/views/knihy-roka-pre-deti-vo-veku-7-10-rokov.pug, app/views/knihy-roka-reportaz-a-literatura-faktu.pug, app/views/knihy-roka-tipy-vydavatelov.pug, app/views/mixins/knihy-roka/introduction.pug, app/views/mixins/knihy-roka/partialBeletriaPage.pug, app/views/mixins/knihy-roka/partialDetiPage.pug
Aby nam to fungovalo aj z martinus.sk
=> Knihy roka 2020: Absolutna cesta pre obrazky

app/styles/layout/_sections.scss
Dakujeme zakaznikovi za jednoduchy fix collapsnutych komentarov.
https://www.wrike.com/open.htm?id=588949840
=> Fixnutie .collapsed v niektorych browseroch

app/views/mixins/knihy-roka/checkoutModal.pug, app/views/mixins/knihy-roka/modalContent.pug
Opat dufam, ze som spravne pochopil zadanie.
3. Toto som si cestne jeziskovske myslela, ze budeme mat, ale asi sa sme sa nematchli komunikacne: aj v modali produktu, ktory NEMA citaciu s fotkou, chceme mat v modrej bubline „vseobecny Martinus“ text. Takto sa nestane, ze produkty, ktore su na webe v moduli „riadok“ ostanu bez nasho custom textu. Tomu by som sa chcela vyhnut, lebo tie texty su pointa = nasa odbornost. Pridavam do prilohy aj obrazok.
=> show modal description if review is not available

app/scripts/modules/Tooltip.js
Malo by vyriesit tieto bugy s oseknutym tooltipom:
- https://www.wrike.com/open.htm?id=597785113
- https://www.wrike.com/open.htm?id=603685099 (2. bug)
=> Append tooltip na body, namiesto parent

app/views/category-new.pug
=> Drobné fixy na novej hlavičke kategórií

app/views/category-new.pug, app/views/modules/category-list-new.pug
- Namiesto "Naše top" zobrazíme na desktope ikonku domčeka
- Pridané info o počte výsledkov
https://www.wrike.com/open.htm?id=650794429
=> Drobné zmeny v sorte nového listingu

app/styles/utils/_config.scss, app/styles/utils/_variables.scss
https://www.wrike.com/open.htm?id=709866248
=> Napraví z-index pre dropdown

package.json, yarn.lock
Reverts martinusdev/styleguide#80
=> Revert "Bump swiper from 3.4.2 to 6.5.1"

app/scripts/modules/Select.js, app/styles/vendors/Choices/choices.scss, app/views/modules/card-cart.pug
- zrušené obmedzenie width
- zarovnanie doprava
=> CaC: Krajšie vykreslí store select

app/scripts/modules/Modal.js
https://www.wrike.com/open.htm?id=750469692
=> Event za zatvorenie modalu pocuva na mousedown a nie click

app/styles/pages/_buybacks.scss, app/views/buybacks-lp.pug
https://www.wrike.com/open.htm?id=710804618
=> Knihovrátok LP: Ešte viac ladenia

app/styles/pages/_buybacks.scss, app/views/buybacks-lp.pug
https://www.wrike.com/open.htm?id=710804618
=> Knihovrátok LP: Zopár drobných vyladení

app/scripts/modules/FontAwesome.js, app/views/buybacks-lp.pug, app/views/styleguide/data/font-awesome-subset.yaml
https://www.wrike.com/open.htm?id=710804618
=> Knihovrátok LP - doplnené ikonky

app/styles/main.scss, app/styles/utils/_mixins_functions.scss
Rovnako pomenovane mixiny sa pretazili bootstrapovskymi, cim sa niektore komponenty rozhasili
=> Upravi poradie loadovania mixinov

app/styles/_utilities.scss, app/styles/light.scss, app/styles/tools/_utilities.scss, app/styles/utils/_config.scss, app/views/campaign-pomocnik-step1.pug, app/views/campaign-pomocnik-step2.pug, app/views/campaign-pomocnik-step3.pug, app/views/category-new.pug, app/views/editorial.pug, app/views/mixins/knihy-roka/backgroundSection.pug, app/views/mixins/knihy-roka/bookHorizontal.pug, app/views/mixins/knihy-roka/bookVertical.pug, app/views/mixins/productHorizontal.pug, app/views/modules/category-list-new.pug, app/views/modules/category-list.pug, app/views/modules/checkout-notice.pug, app/views/modules/header/megamenu.pug, app/views/styleguide/badges.pug, app/views/styleguide/icons.pug, app/views/styleguide/price-box.pug, app/views/styleguide/utilities.pug
zjednotenie nazvoslovia farieb, doplnenie chybajucich variantov, error badge
https://www.wrike.com/open.htm?id=478736847
=> Text color utility upravy

app/styles/modules/_tooltips.scss, app/styles/tools/_utilities.scss, app/views/styleguide/tooltips.pug
Davnejsim bumpom verzie tippy.js sa stratili nejake nastavenia temy kvoli zmene syntaxe
=> Opravi classy pre tippy temu

app/styles/pages/_buybacks.scss
Bilo sa to s ikonou ktorá sa volala icon-circle
https://www.wrike.com/open.htm?id=782738820
=> Zmení názvoslovie pre icon-circle

app/styles/xmas.scss, app/views/campaign-pomocnik-thankyou-xmas.pug, app/views/campaign-pomocnik-thankyou.pug
https://www.wrike.com/open.htm?id=766080075
=> Vianočný pomocník: Fix thank you page

app/styles/knihy-roka.scss
Wrike: https://www.wrike.com/open.htm?id=777768910
tl;dr Požiadavka je zmeniť a prehodiť písmo v hero banneri, takže naprv musím spraviť úpravu v (s)css a potom aj úpravu v template.
=> Zmena veľkosti h1 pre Knihy roka.

app/styles/sections/_header.scss, app/views/mixins/userMenu.pug
https://www.wrike.com/open.htm?id=791152380
=> Opraví max. výšku my account dropdownu

app/styles/banners.scss, app/views/banners.pug, yarn.lock
https://www.wrike.com/open.htm?id=673000497
=> Partner banners updates 2

app/styles/review-cards.scss
https://www.wrike.com/open.htm?id=812660955
=> Opraví layout review cards

app/styles/utils/_config.scss
https://www.wrike.com/open.htm?id=769519558
=> Mierne zväčší label font-size

app/scripts/modules/Select.js, app/styles/components/_map.scss, app/styles/utils/_config.scss, app/views/modules/checkout/delivery-picker-modal.pug
[Wrike](https://www.wrike.com/open.htm?id=632200501)
=> Picker OO: Úpravy modalu a scrollu

app/styles/modules/_cards.scss, app/views/layouts/_default.pug, app/views/layouts/index.pug, app/views/styleguide/templates/layout.pug
=> Umožní používať font awesome v css pseudo elementoch

app/styles/modules/_dropdown.scss, app/styles/vendors/Choices/choices.scss, app/views/layouts/_default.pug, app/views/layouts/index.pug, app/views/styleguide/templates/layout.pug
https://www.wrike.com/open.htm?id=902445027
=> Fa ikonky: Upravene loadovanie ikoniek v css

app/styles/components/_breadcrumbs.scss, app/styles/layout/_sections.scss, app/views/mixins/breadcrumbs.pug
https://www.wrike.com/open.htm?id=921993883
=> Breadcrumbs: Menšie písmo a padding na mobile

app/styles/modules/_buttons.scss, app/styles/utils/_config.scss, app/views/styleguide/buttons.pug
Zjednotí veľkosť buttonov obsahujúcich font awesome ikonku s buttonmi bez ikonky
=> Zjednotí veľkosť buttonov

app/styles/utils/_config.scss
=> Badge: teal farba + doplnena teal farba do $color-presets

app/styles/components/_listing.scss, app/styles/main.scss, app/styles/modules/_badges.scss, app/views/category.pug, app/views/data/books.yaml, app/views/data/sitemap.yaml, app/views/list-publisher.pug, app/views/modules/category-list.pug, app/views/search-results.pug
https://www.wrike.com/open.htm?id=870208807
=> Listing: New layout

app/styles/knihy-roka.scss
https://www.wrike.com/open.htm?id=984006582
Deploy PR nasledne.
=> Hero bannery pre Knihy roka 2022

app/styles/components/_product.scss, app/views/mixins/product.pug, app/views/modules/category-list.pug, app/views/modules/club-profile.pug
Using negative margins instead of absolute positioning, to retain correct bounding box of the cover element
=> Product cover collection: Redesign

app/styles/campaigns/_tajomne-kniznice.scss, app/views/campaign-tajomne-kniznice-answer.pug
- inset shadow for an enhanced mystique feel
- tweaked positioning of backgrounds
- larger hero image and book cover
=> Campaign 2023: Visual enhancements

app/scripts/font-awesome.js, app/scripts/modules/Alert.js, app/styles/modules/_alerts.scss, app/views/mixins/loader.pug, app/views/styleguide/alerts.pug, app/views/styleguide/data/font-awesome-subset.yaml
- better color definitions
- use font awesome
- unified and streamlined
=> Alerts: Refactoring

app/styles/utils/_config.scss, app/views/homepage.pug
=> Tab button groups: More obvious active state

app/styles/components/_mega-menu.scss, app/views/detail-knihy.pug, app/views/homepage.pug, app/views/layouts/_default.pug, app/views/modules/header/megamenu.pug
=> Megamenu: Mobile redesign

app/scripts/modules/Tab.js, app/views/styleguide/tabs.pug
https://www.wrike.com/open.htm?id=1152542584
=> Fix Tabs behavior on external tab links

app/styles/components/_cms-article.scss
.btn should not have blue text color
=> CMS Article link fix

app/styles/sections/_header.scss
https://www.wrike.com/open.htm?id=1214672743
=> Search form: fix margin

app/scripts/modules/Clipboard.js
https://github.com/martinusdev/styleguide/assets/2431529/412fb16a-1387-428b-b7eb-e9342a88f6c2
=> Clipboard - uprava sposobu zobrazenia feedbacku

dist/rev-manifest.json
rev-manifest pre https://github.com/martinusdev/styleguide/pull/426
=> New process BG image build rev manifest

app/scripts/main.js, app/styles/main.scss, app/styles/utils/_config.scss, app/styles/utils/_variables.scss, app/views/offcanvas.pug
https://getbootstrap.com/docs/5.3/components/offcanvas
=> Support for Bootstrap Offcanvas

app/styles/modules/_lists.scss, app/views/styleguide/lists.pug
=> New list type: checkmark

app/styles/modules/_lists.scss, app/views/styleguide/lists.pug
Reverts martinusdev/styleguide#439
Nakoniec ideme inou cestou
=> Revert "New list type: checkmark"

app/styles/modules/_buttons.scss, app/styles/modules/_tabs.scss, app/styles/utils/_config.scss, app/views/styleguide/tabs.pug, package.json, yarn.lock
- default merged with compact
- new btn-group--tab:
=> Tab changes

app/scripts/modules/ProductPreview.js
- space / down / right = next page
- shift+space / up / left = previous page
=> ProductPreview: Navigate using keyboard

app/styles/utils/_config.scss, app/views/modules/header/header.pug, app/views/modules/header/megamenu.pug
=> Unify focus states

app/scripts/modules/Tooltip.js
https://www.wrike.com/open.htm?id=1449814006
=> Fix tooltip loading

app/views/data/sitemap.yaml, app/views/newsletter.pug
https://www.wrike.com/open.htm?id=1469610868
=> Newsletter signup page

app/scripts/modules/Alert.js
- added correct aria role="alert"
- added closeText for the close button
=> Alert accessibility updates

app/scripts/modules/Alert.js
- ability to close alerts by pressing Escape
- a bit of refactoring
- loader will have role="status" so it doesn't get announced so heavily
=> Accessible alerts - updates

app/styles/components/_map.scss, app/styles/components/_shell.scss, app/styles/knihy-roka.scss, app/styles/layout/_sections.scss, app/styles/tools/_utilities.scss, app/styles/utils/_config.scss, package.json, yarn.lock
- styles moved and cleaned up from shame.css in eshop
- homepage adjustments
- updated font awesome
=> Various updates

app/styles/base/_globals.scss, app/styles/layout/_sections.scss, app/styles/utils/_config.scss, app/views/homepage-2024.pug
- changing from :focus to :focus-visible
- introducing variable for changing the outline color
- new homepage outline color on dark backgrounds will be white
- 1px default outline offset
=> Focus state outline updates

app/styles/campaigns.scss, app/styles/campaigns/_knizne-putovanie.scss, app/views/campaign-2024-auth.pug, app/views/campaign-2024-layout.pug
https://www.wrike.com/open.htm?id=1526771127
=> Campaign 2025: Diary paper background

app/styles/components/_product.scss, app/views/mixins/productResponsive.pug, app/views/styleguide/data/sitemap.yaml, app/views/styleguide/product-card.pug
Added accessible styling to the .product--responsive element - the whole card will act as a link via pseudo-element (instead of just the title).
=> Added .product--responsive info to a new styleguide page.

app/styles/base/_typography.scss, app/views/styleguide/typography.pug
https://www.wrike.com/open.htm?id=1648113739
=> New: Divider headline

app/scripts/main.js, app/scripts/modules/FeatureHighlight.js, app/scripts/modules/Tooltip.js, app/styles/modules/_tooltips.scss, app/views/styleguide/data/sitemap.yaml, app/views/styleguide/tooltips.pug
https://www.wrike.com/open.htm?id=1598908227
=> New: "Feature highlight" tooltip module

app/scripts/modules/Clipboard.js, app/scripts/modules/Tooltip.js, app/scripts/modules/Utils.js, package.json
=> Modernize Clipboard and Utils

app/styles/components/_product.scss, app/styles/components/_shell.scss, app/styles/modules/_buttons.scss, app/styles/modules/forms/_global.scss, app/styles/tools/_utilities.scss, app/styles/utils/_config.scss, package.json, yarn.lock
- Moving some shame.css styles to their respective places
- Small package updates
=> Housekeeping

app/styles/components/_listing.scss, app/styles/utils/_config.scss
https://www.wrike.com/open.htm?id=1732664517
=> Cover size adjustments
